Repository basketini-jones/duke, pull requests merged in 2022-04, with the labels that each got.

#71 Implement devil deal graphics
  duke.lua
  resources/gfx/ui/devilprices.png
  resources/gfx/ui/fly_devil_deal_price.anm2
Labels: feature, awaiting graphics

#72 Implement pog for good items
  content/costumes2.xml
  main.lua
  resources/gfx/characters/costume_duke_pog.anm2
  resources/gfx/characters/costumes/costume_duke_pog.png
Labels: feature, awaiting graphics

#67 Add eternal flies giantbook anim
  duke.lua
  flies/eternal.lua
  helpers/achievements.lua
  helpers/giantbook.lua
  main.lua
  resources-dlc3/giantbook.xml
  resources/gfx/ui/achievements/achievement.anm2
  resources/gfx/ui/achievements/achievement_placeholder.png
  resources/gfx/ui/achievements/achievements.anm2
  resources/gfx/ui/achievements/frame.png
  resources/gfx/ui/achievements/paper_plus.png
  resources/gfx/ui/giantbook/effect_010_poof02.png
  resources/gfx/ui/giantbook/empty-book.anm2
  resources/gfx/ui/giantbook/giantbook.anm2
  resources/gfx/ui/giantbook/giantbook_eternalfly.anm2
  resources/gfx/ui/giantbook/giantbook_heartflies.png
  resources/gfx/ui/giantbook/rune_07_berkand.png
Labels: awaiting implementation

#69 EID and Encyclopedia Support
  cards/tapewormCard.lua
  content/gfx/ui_cardfronts.anm2
  content/gfx/ui_duke_cardfronts.png
  helpers/docs.lua
  items/dukesGullet.lua
  items/othersGullet.lua
  items/thePrinces.lua
  main.lua
  resources/gfx/ui/eid_card_fronts.anm2
  trinkets/dukesTooth.lua
Labels: feature

#78 Implement Lil Duke
  content/entities2.xml
  content/items.xml
  entityVariants/lilDuke.lua
  entityVariants/registry.lua
  flies.lua
  items/lilDuke.lua
  items/registry.lua
  main.lua
  resources/gfx/familiars/lil_duke.anm2
  resources/gfx/familiars/lil_duke.png
  resources/gfx/items/collectibles/lil_duke.png
Labels: feature

#79 Custom items now appear in item pools
  content/itempools.xml
Labels: feature

#81 Add Duke Flute
  content/entities2.xml
  content/sounds.xml
  entityVariants/friendlyDuke.lua
  entityVariants/lilDuke.lua
  entityVariants/registry.lua
  items/dukeFlute.lua
  items/registry.lua
  main.lua
  resources/gfx/familiars/effect_052_dust cloud.png
  resources/gfx/familiars/friendly_duke.anm2
  resources/gfx/familiars/friendly_duke.png
  resources/gfx/familiars/friendly_duke_green.png
  resources/gfx/familiars/friendly_duke_orange.png
  resources/sfx/duke_flute.wav
  sounds/registry.lua
Labels: feature

#60 Implement infested heart (formerly hollow heart)
  duke.lua
  helpers/flies.lua
  helpers/utils.lua
  resources/gfx/items/trinkets/infested_heart.png
  resources/gfx/ui/achievements/achievement_infestedHeart.png
  trinkets/infestedHeart.lua
  trinkets/registry.lua
  unlocks/infestedHeart.lua
  unlocks/registry.lua
  unlocks/swarmBaby.lua
Labels: feature

#82 Implement super infestation
  helpers/utils.lua
  items/registry.lua
  items/superInfestation.lua
Labels: feature

#85 Add death item gfx for items
  content/gfx/controls.png
  content/gfx/death items.anm2
  content/gfx/death items.png
  content/items.xml
  resources/gfx/familiars/fiendish_heart_fly.png
Labels: feature

#86 Implement Sharty McFly
  content/entities2.xml
  entityVariants/lovePoop.lua
  entityVariants/registry.lua
  entityVariants/shartyMcFly.lua
  items/registry.lua
  items/shartyMcFly.lua
  resources/gfx/familiars/love_poop.anm2
  resources/gfx/familiars/love_poop.png
  resources/gfx/familiars/love_poopspawn.png
  resources/gfx/familiars/sharty_mcfly.anm2
  resources/gfx/familiars/sharty_mcfly.png
  resources/gfx/items/collectibles/sharty_mcfly.png
Labels: feature
