Repository basketini-jones/duke, pull requests merged in 2022-07, with the labels that each got.

#123 Fix -5 and -6 pickup prices
  duke.lua
  fuck.lua
  helpers/utils.lua
  husk.lua
  main.lua
Labels: bug

#122 Redo unlocks system
  cards/redTapewormCard.lua
  cards/soulOfDuke.lua
  cards/tapewormCard.lua
  flyHearts.lua
  helpers/unlocks.lua
  helpers/utils.lua
  items/dukeFlute.lua
  items/dukeOfEyes.lua
  items/fiendishSwarm.lua
  items/lilDuke.lua
  items/lilHusk.lua
  items/othersGullet.lua
  items/othersRottenGullet.lua
  items/queenFly.lua
  items/shartyMcFly.lua
  items/superInfestation.lua
  items/theInvader.lua
  items/thePrinces.lua
  items/ultraHeartFly.lua
  main.lua
  resources/gfx/ui/achievements/achievement_dukeBaby.png
  resources/gfx/ui/achievements/achievement_dukeOfEyes.png
  resources/gfx/ui/achievements/achievement_flyHearts.png
  resources/gfx/ui/achievements/achievement_huskBaby.png
  resources/gfx/ui/achievements/achievement_mosquito.png
  resources/gfx/ui/achievements/achievement_othersGullet.png
  resources/gfx/ui/achievements/achievement_othersRottenGullet.png
  resources/gfx/ui/achievements/achievement_redTapewormCard.png
  resources/gfx/ui/achievements/achievement_soulOfDuke.png
  resources/gfx/ui/achievements/achievement_swarmBaby.png
  resources/gfx/ui/achievements/achievement_theInvader.png
  trinkets/dukesTooth.lua
  trinkets/infestedHeart.lua
  trinkets/mosquito.lua
  trinkets/pocketOfFlies.lua
  unlocks/dukeBaby.lua
  unlocks/dukeFlute.lua
  unlocks/dukesGullet.lua
  unlocks/dukesTooth.lua
  unlocks/fiendishSwarm.lua
  unlocks/huskBaby.lua
  unlocks/infestedHeart.lua
  unlocks/lilDuke.lua
  unlocks/queenFly.lua
  unlocks/registry.lua
  unlocks/shartyMcFly.lua
  unlocks/superInfestation.lua
  unlocks/swarmBaby.lua
  unlocks/tapewormCard.lua
  unlocks/thePrinces.lua
Labels: chore

#126 add the rest of the achievement gfx
  resources/gfx/ui/achievements/achievement_dukeOfEyes.png
  resources/gfx/ui/achievements/achievement_fiendishSwarm.png
  resources/gfx/ui/achievements/achievement_flyHearts.png
  resources/gfx/ui/achievements/achievement_infestedHeart.png
  resources/gfx/ui/achievements/achievement_mosquito.png
  resources/gfx/ui/achievements/achievement_othersRottenGullet.png
  resources/gfx/ui/achievements/achievement_redTapewormCard.png
  resources/gfx/ui/achievements/achievement_soulOfDuke.png
  resources/gfx/ui/achievements/achievement_theInvader.png
  resources/gfx/ui/achievements/raws/achievements0001.png
  resources/gfx/ui/achievements/raws/achievements0002.png
  resources/gfx/ui/achievements/raws/achievements0003.png
  resources/gfx/ui/achievements/raws/achievements0004.png
  resources/gfx/ui/achievements/raws/achievements0005.png
  resources/gfx/ui/achievements/raws/achievements0006.png
  resources/gfx/ui/achievements/raws/achievements0007.png
  resources/gfx/ui/achievements/raws/achievements0008.png
  resources/gfx/ui/achievements/raws/achievements0009.png
  resources/gfx/ui/achievements/raws/achievements0010.png
  resources/gfx/ui/achievements/raws/achievements0011.png
  resources/gfx/ui/achievements/raws/achievements0012.png
  resources/gfx/ui/achievements/raws/achievements0013.png
  resources/gfx/ui/achievements/raws/achievements0014.png
  resources/gfx/ui/achievements/raws/achievements0015.png
  resources/gfx/ui/achievements/raws/achievements0016.png
  resources/gfx/ui/achievements/raws/achievements0017.png
Labels: enhancement

#130 Add EID and Encyclopedia Descriptions
  cards/redTapewormCard.lua
  cards/soulOfDuke.lua
  cards/tapewormCard.lua
  duke.lua
  helpers/docs.lua
  husk.lua
  items/dukeFlute.lua
  items/dukeOfEyes.lua
  items/dukesGullet.lua
  items/fiendishSwarm.lua
  items/lilDuke.lua
  items/lilHusk.lua
  items/othersGullet.lua
  items/othersRottenGullet.lua
  items/queenFly.lua
  items/rottenGullet.lua
  items/shartyMcFly.lua
  items/superInfestation.lua
  items/theInvader.lua
  items/thePrinces.lua
  items/ultraHeartFly.lua
  main.lua
  trinkets/dukesTooth.lua
  trinkets/infestedHeart.lua
  trinkets/mosquito.lua
  trinkets/pocketOfFlies.lua
Labels: documentation
