Repository basketini-jones/duke, pull requests merged in 2022-06, with the labels that each got.

#104 Add passive item costumes and death item sprites for new items
  content/costumes2.xml
  content/gfx/death items.anm2
  content/gfx/death items.png
  content/items.xml
  helpers/flies.lua
  resources/gfx/characters/costume_duke_of_eyes.anm2
  resources/gfx/characters/costume_queen_fly.anm2
  resources/gfx/characters/costume_super_infestation.anm2
  resources/gfx/characters/costumes/costume_duke_of_eyes.png
  resources/gfx/characters/costumes/costume_queen_fly.png
  resources/gfx/characters/costumes/costume_super_infestation_body.png
  resources/gfx/characters/costumes/costume_super_infestation_head.png
  resources/gfx/characters/costumes_apollyon/costume_super_infestation_head.png
  resources/gfx/characters/costumes_bluebaby/costume_super_infestation_head.png
  resources/gfx/characters/costumes_duke/costume_duke_of_eyes.png
  resources/gfx/characters/costumes_duke/costume_super_infestation_head.png
  resources/gfx/characters/costumes_duke_b/costume_duke_of_eyes.png
  resources/gfx/characters/costumes_duke_b/costume_super_infestation_head.png
  resources/gfx/characters/costumes_forgotten/costume_super_infestation_head.png
  resources/gfx/characters/costumes_keeper/costume_super_infestation_head.png
  resources/gfx/characters/costumes_shadow/costume_duke_of_eyes.png
  resources/gfx/characters/costumes_shadow/costume_super_infestation_head.png
  resources/gfx/items/collectibles/queen_fly.png
  wisps.lua
Labels: enhancement

#103 Implement Red Tapeworm
  cards/redTapewormCard.lua
  cards/registry.lua
  helpers/husk.lua
  helpers/utils.lua
  items/rottenGullet.lua
Labels: feature

#102 Implement Duke of Eyes
  helpers/partitions.lua
  helpers/spiders.lua
  helpers/utils.lua
  items/dukeOfEyes.lua
  resources/gfx/tears/dukeOfEyes.png
  resources/gfx/tears/dukeOfEyesTear.anm2
Labels: feature, awaiting graphics

#106 Implement mosquito
  cards/registry.lua
  trinkets/mosquito.lua
  trinkets/registry.lua
Labels: feature

#109 Add Lil Husk
  content/entities2.xml
  entityVariants/lilDuke.lua
  entityVariants/lilHusk.lua
  entityVariants/lovePoop.lua
  entityVariants/registry.lua
  entityVariants/shartyMcFly.lua
  flies.lua
  helpers/flies.lua
  helpers/spiders.lua
  items/lilHusk.lua
  items/registry.lua
  main.lua
  resources/gfx/familiars/lil_husk.anm2
  resources/gfx/familiars/lil_husk.png
  resources/gfx/familiars/love_poop.anm2
Labels: feature

#113 Updated fly registry to do some more stuff a bit better, just test that flies are working properly
  flies/black.lua
  flies/blended.lua
  flies/bone.lua
  flies/eternal.lua
  flies/fiendish.lua
  flies/modded/immortal.lua
  flies/modded/moonlight.lua
  flies/registry.lua
  items/fiendishSwarm.lua
  main.lua
  spiders/registry.lua
Labels: chore

#111 Add Fly Hearts
  duke.lua
  flies/doubleRed.lua
  flies/halfRed.lua
  flies/halfSoul.lua
  flies/modded/doublePatched.lua
  flies/modded/doubleWeb.lua
  flies/modded/patched.lua
  flies/registry.lua
  flies/scared.lua
  flyHearts.lua
  helpers/utils.lua
  main.lua
  resources/gfx/familiars/heart_fly.anm2
  trinkets/infestedHeart.lua
Labels: awaiting graphics
